### ISSUE TITLE
Bullet Spawn Point: darf nicht in der Wand sein

### ISSUE THREAD

**Issue by kathi045** [kathi045/GravityFlip#4]

**Comment by romanha** [comment]
wieso?

**Comment by kathi045** [comment]
weil man dann nicht schießen kann.. wärs nicht besser, man collidet schon vorher? Mit der Gun als Grenze?

**Comment by romanha** [comment]
achso, weil man ja auch in die andere richtung schießen könnte. kann ich beim nächsten push gleich mitfixen.
